### ISSUE TITLE
Why not using the variable csv-separators provided by csv-mode?

### ISSUE THREAD

**Issue by seblemaguer** [emacs-vs/rainbow-csv#1]
Hello,

thanks a lot for this really nice package. I was wondering, is there a reason why you didn't use `csv-separators` provided by the package `csv-mode` as the entry to define the separators instead of redefining them manually? I just want to be sure I don't miss anything if I want to use this variable :)

Thanks a lot

**Comment by jcs090218** [comment]
They are simply different types. `csv-separators` is a list of strings, but the separator in this package requires a character. We can use this variable with this package, but I couldn't think of an ideal condition to lock this variable to this package. Any suggestions are welcome! :)

**Comment by seblemaguer** [comment]
thanks for the answer. I will try to think about something (may take a while though...). If you are ok with it, I leave the issue open for now but if it is annoying for you (which I definitely understand), don't hesitate to close it.

**Comment by jcs090218** [comment]
Not at all. Feel free to leave this issue open as long as you like! ;)

**Comment by abougouffa** [comment]
For me, I'm using this snippet to automatically set the separator for `csv-mode` and `rainbow-csv-mode`.

```elisp
;; Automatically guess the separator
(add-hook 'csv-mode-hook #'csv-guess-set-separator)

;; Use the same guessed separator for `rainbow-csv-mode'
(defun +rainbow-csv--set-separators:after-csv-set-separator-a (&rest args)
  (setq-local rainbow-csv-separators `((,major-mode \, sep))))
(advice-add #'csv-set-separator :after #'+rainbow-csv--set-separators:after-csv-set-separator-a)))
```

**Comment by seblemaguer** [comment]
thanks a lot @abougouffa for solving this :)
