### ISSUE TITLE
Feature Request: Make separator character customizable

### ISSUE THREAD

**Issue by fleimgruber** [emacs-vs/rainbow-csv#4]
As a user I want to view a CSV file that has a different separator character than ",", e.g. ";".

Currently the separator character for CSV files is hardcoded to be "," https://github.com/emacs-vs/rainbow-csv/blob/e6213ceebe75d862535ae527d7472d5c33cb261e/rainbow-csv.el#L116

**Comment by jcs090218** [comment]
I'll make the changes.

Feel free to open a PR for this since I've been a little busy recently.

**Comment by jcs090218** [comment]
Added in #5.

**Comment by fleimgruber** [comment]
Thanks for the quick response and implementation!
